name: Selenium Firefox Scraping

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-scraping:
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Firefox and GeckoDriver
      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          sudo apt-get install -y wget
          wget https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.32.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the scraper script
      - name: Run scraper
        run: |
          python your_script.py
